import numpy as np
a=np.array(input("enter the matrix a :"))
b=np.array(input("enter the matrix b :"))
c=np.add(a,b)
d=np.subtract(a,b)
e=np.multiply(a,b)
f=np.divide(a,b)
g=np.linalg.det(a)
h=np.linalg.inv(a)
i=np.linalg.eig(a)
j=np.trace(a)
k=np.linalg.matrix_rank(a)
l=np.transpose(a)
print ("addtion of two matrix",c)
print ("subtraction of two matrix",d)
print ("multiplication of two matrix",e)
print ("division of two matrix",f)
print ("determinant of matrix",g)
print ("inverse of matrix",h)
print ("eigen values of matrix",i)
print ("trace of matrix",j)
print ("rank of the matrix",k)
print ("transpose of the matrix",k)
